# This is a basic workflow to help you get started with Actions

name: Daily Charts Build

on: [push]
#  schedule:
#    - cron: '0 3 * * *'

jobs:
  build_charts:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Restore dependencies from cache
    - uses: actions/cache@v1
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Global Time Series
      run: |
        python scripts/covid_time_analysis_global.py

    - name: Run United States Time Series
      run: |
        python scripts/covid_time_analysis_us.py

#    - name: Run Clinical
#      run: |
#        python scripts/clinical.py

    - name: Generate new index.html
      run: |
        python scripts/gen_index.py

    - name: Push changes to repo
      run: |
        REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"

        git pull ${REMOTE}
        git checkout master
        git add .
        git status
        git commit -am "daily update"
        git push ${REMOTE} master